apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "segment-gatherer.fullname" $ }}-{{ .Values.configMap.nameSuffix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "segment-gatherer.fullname" . }}
    {{- include "segment-gatherer.labels" . | nindent 4 }}
data:
  segment-gatherer: |
{{ .Values.configMap.data.sg | nindent 4 }}
