apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "segment-gatherer.fullname" . }}-env
data:
  env-variables: |
    export MESSAGE_SOURCE=tcp://segment-gatherer-fci:40000
    export SATPY_CONFIG_PATH=/config/satpy
    export PSP_CONFIG_FILE=/config/pyspectral.yaml
    export POSTTROLL_TCP_KEEPALIVE="1"
    export POSTTROLL_TCP_KEEPALIVE_CNT="10"
    export POSTTROLL_TCP_KEEPALIVE_IDLE="1"
    export POSTTROLL_KEEPALIVE_INTVL="1"