product_list:
  output_dir:
    /mnt/output/
  subscribe_topics:
    - /dataset/fci_nc
  publish_topic: /image/fci_nc
  reader: fci_l1c_nc
  fname_pattern:
    "{start_time:%Y%m%d_%H%M}_{platform_name}_{areaname}_{productname}.{format}"
  # Delay composite generation until resampling is done.  This is
  # faster when many products share the same channels
  delay_composites: True
  resampler: gradient_search

  areas:
    nordsat_3857_850m:
      # Add a priority. Not relevant for one area, but just to show the option
      priority: 1
      areaname: nordsat_3857_850m

      products:
        true_color_day:
          productname: true_color_day
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG
        cloud_phase_day:
          productname: cloud_phase_day
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG
        cimss_cloud_type_day:
          productname: cimss_cloud_type_day
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG
        natural_color_day:
          productname: natural_color_day
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG

    nordsat_3857_1.7km:
      # Add a priority. Not relevant for one area, but just to show the option
      priority: 1
      areaname: nordsat_3857_1.7km

      products:
        day_essl_low_level_moisture:
          productname: day_essl_low_level_moisture
          formats:
            - format: tif
              writer: geotiff
              compress: JPEG
              quality: 95
              driver: COG
        colorized_ir_clouds:
          productname: colorized_ir_clouds
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG
        sandwich_day:
          productname: sandwich_day
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG

    nordsat_3857_3.4km:
      priority: 1
      areaname: nordsat_3857_3.4km

      products:
        airmass:
          productname: airmass
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG
        night_fog_night:
          productname: night_fog_night
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG
        24h_microphysics:
          productname: 24h_microphysics
          formats:
            - format: tif
              writer: geotiff
              compress: WEBP
              quality: 95
              driver: COG


workers:
  - fun: !!python/name:trollflow2.plugins.create_scene
  - fun: !!python/name:trollflow2.plugins.sza_check
  - fun: !!python/name:trollflow2.plugins.load_composites
  - fun: !!python/name:trollflow2.plugins.resample
  - fun: !!python/name:trollflow2.plugins.save_datasets
  - fun: !!python/object:trollflow2.plugins.FilePublisher {port: 10009, nameservers: false}