apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trollflow2.fullname" $ }}-{{ .Values.configMap.nameSuffix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "trollflow2.fullname" . }}
    {{- include "trollflow2.labels" . | nindent 4 }}
data:
  trollflow2: |
{{ .Values.configMap.data.tf2 | nindent 4 }}
