apiVersion: v1
kind: Service
metadata:
  name: {{ include "trollflow2.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trollflow2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "trollflow2.fullname" . }}
